"""Export API — generate PDF, Markdown, and CSV reports from chat responses."""

import csv
import io
import json
import logging
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/export", tags=["export"])


class ExportRequest(BaseModel):
    title: str = "Kapitali Report"
    content: str
    format: str = "markdown"  # markdown, csv, json
    sources: list[dict] = []


@router.post("/generate")
async def export_report(req: ExportRequest):
    """Generate a report in the requested format."""
    if req.format == "markdown":
        md = f"# {req.title}\n\n> Generated by Kapitali — Intelligence for Capital\n\n---\n\n{req.content}\n"
        if req.sources:
            md += "\n\n---\n\n## Sources\n\n"
            for i, src in enumerate(req.sources, 1):
                md += f"{i}. **{src.get('title', 'Unknown')}** — {src.get('snippet', '')}\n"
        return StreamingResponse(
            io.BytesIO(md.encode("utf-8")),
            media_type="text/markdown",
            headers={"Content-Disposition": f'attachment; filename="{req.title}.md"'},
        )

    elif req.format == "csv":
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["Section", "Content"])
        writer.writerow(["Title", req.title])
        for line in req.content.split("\n"):
            if line.strip():
                writer.writerow(["", line.strip()])
        if req.sources:
            writer.writerow([])
            writer.writerow(["Source", "Details"])
            for src in req.sources:
                writer.writerow([src.get("title", ""), src.get("snippet", "")])
        return StreamingResponse(
            io.BytesIO(output.getvalue().encode("utf-8")),
            media_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="{req.title}.csv"'},
        )

    elif req.format == "json":
        data = {
            "title": req.title,
            "content": req.content,
            "sources": req.sources,
            "generated_by": "Kapitali",
        }
        return StreamingResponse(
            io.BytesIO(json.dumps(data, indent=2).encode("utf-8")),
            media_type="application/json",
            headers={"Content-Disposition": f'attachment; filename="{req.title}.json"'},
        )

    else:
        raise HTTPException(status_code=400, detail=f"Unsupported format: {req.format}")
